### ISSUE TITLE
Timezone settings

### ISSUE THREAD

**Issue by ruthan** [mrHobbY/DI-clan-helper#3]
That -X, or +X hours settings is really confusing you can just set some timezone it would be much better.. there is not even preview of times which you would get..
  What supposed to be Time channel is over my head. What supposed to be game time or lobby or none setings?
   I see game time value there 10:15 PM, here is 4:20 AM..
   
   Support for optimal 24 hour time, without AM and PM would be nice too..

**Comment by ruthan** [comment]
Hmm, i saw update.. there is nice Europe setings but time seems broken.. or it need to regenerate, i changed and saved setting.. Its supposed to refresh right way? Or need i wait on some event time, or its there some force refresh option?

**Comment by mrHobbY** [comment]
My bad. There was an issue last night with DB. Check now.  Also come to https://discord.gg/tBGFbBUZsC  and let's work it out live

**Comment by ruthan** [comment]
I thing that is still messed up, logically, there are two offsets in the play, GMT -6 (old settings) and GMT+1 new settings.. 
  
![image](https://user-images.githubusercontent.com/1702944/213844860-ad66eba0-07e7-43dd-99ba-b8c1b1655a2d.png)

  Time are wrong for sure..
  
  There are 5 global events today (Friday, January 20)
Ancient Nightmare at 5:00 AM 7:00 PM 3:30 AM 
Assembly at 2:00 AM 
Battleground at 3:00 PM 7:00 PM 1:00 AM 5:00 AM 
The Vault at 7:00 PM 2:00 AM 
Wrathborne Invasion at 7:30 PM 4:00 AM

**Comment by ruthan** [comment]
It seems fixed now.
